# Mage Inferno Docker Compose (https://github.com/mageinferno/magento2-docker-compose)
# Version 4.1.1

app:
  image: mageinferno/magento2-nginx:1.10.1-0
  links:
    - phpfpm
    - db
  volumes_from:
    - appdata
  labels:
    com.evalent.use-haproxy: ''
    com.evalent.domains: 'test-2.dock.dev' # one domain, or "domain.org, domain.com"
  environment:
    - VIRTUAL_HOST=test-2.dock.dev  # one domain, or "domain.org, domain.com"
#  ports:
#    - 8000:80

appdata:
  image: tianon/true
  volumes:
#    - /srv/www
    - ~/.composer:/var/www/.composer
    - ./www:/srv/www
#    - ./www/app/code:/srv/www/app/code
#    - ./www/app/design:/srv/www/app/design

phpfpm:
  image: mageinferno/magento2-php:7.0.8-fpm-3
  links:
    - db
  volumes_from:
    - appdata
  environment:
    - APP_MAGE_MODE=developer

db:
  image: mariadb:10.1.16
  volumes_from:
    - dbdata
#  ports:
#    - 8001:3306
  environment:
    - MYSQL_ROOT_PASSWORD=magento2
    - MYSQL_DATABASE=magento2
    - MYSQL_USER=magento2
    - MYSQL_PASSWORD=magento2

# phpMyAdmin
phpmyadmin:
  image: nazarpc/phpmyadmin
  environment:
    - VIRTUAL_HOST=pma.test-2.dock.dev
    - MYSQL_ROOT_PASSWORD=magento2
    - MYSQL_HOST=db
  links:
    - db
  labels:
    com.evalent.use-haproxy: ''
    com.evalent.domains: 'pma.test-2.dock.dev'

dbdata:
  image: tianon/true
  volumes:
    - /var/lib/mysql

setup:
  image: mageinferno/magento2-php:7.0.8-fpm-3
  command: /usr/local/bin/mage-setup
  links:
    - db
  volumes_from:
    - appdata
  environment:
    - M2SETUP_DB_HOST=db
    - M2SETUP_DB_NAME=magento2
    - M2SETUP_DB_USER=magento2
    - M2SETUP_DB_PASSWORD=magento2
    - M2SETUP_BASE_URL=http://test-2.dock.dev/ # base url
    - M2SETUP_ADMIN_FIRSTNAME=Admin
    - M2SETUP_ADMIN_LASTNAME=User
    - M2SETUP_ADMIN_EMAIL=dummy@gmail.com
    - M2SETUP_ADMIN_USER=admin
    - M2SETUP_ADMIN_PASSWORD=magento1234
    - M2SETUP_VERSION=2.1.0
    - M2SETUP_USE_SAMPLE_DATA=false
    - M2SETUP_USE_ARCHIVE=false
